### ISSUE TITLE
Configuration by config file

### ISSUE THREAD

**Issue by jpallari** [Lepovirta/lukki#9]

**Comment by keveri** [comment]
Few possibilities:
 - [Jackson](https://github.com/FasterXML/jackson)
 - [snakeyaml](https://bitbucket.org/asomov/snakeyaml)
 - [konf](https://advantageous.github.io/konf/)

**Comment by jpallari** [comment]
There's also:

* [Typesafe Config](https://github.com/typesafehub/config)
* [ini4j](http://ini4j.sourceforge.net/)
* [kaconf](https://github.com/mariomac/kaconf)
* [owner](http://owner.aeonbits.org/)

**Comment by jpallari** [comment]
Settled for JSON
